- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: apt install ros2 dependencies packages
  become: yes
  apt:
    name:
      - curl
      - gnupg2
      - lsb-release

- name: add ROS2 apt repository
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Get Ubuntu Version
  shell: lsb_release -cs
  register: ubuntu_version

- name: add the repository to my sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ubuntu_version.stdout }} main"
    state: present
    filename: ros2.list
    update_cache: yes

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: install ros2
  become: yes
  apt:
    name: ros-humble-desktop

- name: install colcon
  become: yes
  apt:
    name: python3-colcon-common-extensions
