- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Get Ubuntu Version
  shell: lsb_release -cs
  register: ubuntu_version

- name: apt update
  become: yes
  apt:
    update_chache: yes

- name: apt install ros2 dependencies packages
  become: yes
  apt:
    name:
      - curl
      - gnupg2
      - lsb-release

- name: add ROS2 apt repository
  become: yes
  ansible.builtin.apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    state: present
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

- name: add the repository to my sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch={{deb_architecture.stdout}} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ubuntu_version.stdout}} main"
    state: present

- name: apt update
  become: yes
  apt:
    update_chache: yes

- name: install ros2
  become: yes
  apt:
    name: ros-foxy-desktop
  state: present

- name: install cartographer
  become: yes
  apt:
    name: ros-foxy-cartographer
  state: present

- name: install cartographer-ros
  become: yes
  apt:
    name: ros-foxy-cartographer-ros
  state: present

- name: install ecl
  become: yes
  apt:
    name: ros-foxy-ecl-*
  state: present
