- name: apt update
  become: yes
  apt:
    update_chache: yes

- name: apt install locales
  become: yes
  apt:
    name: locales
    state: present

- name: create locale en_US.UTF-8
  locale_gen:
    name: en_US en_US.UTF-8
  
- name: change locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

  

