- name: add_user_to_docker_group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: restart_docker_daemon
  become: yes
  service:
    name: docker
    state: restarted
