- name: clone urg_node
  git:
    repo: https://github.com/Sirius-OIT/urg_node.git
    dest: ../sirius_ws/src/urg_node
    version: foxy-devel

- name: clone urg_c
  git:
    repo: https://github.com/Sirius-OIT/urg_c.git
    dest: ../sirius_ws/src/urg_c
    version: ros2-devel

- name: clone urg_node_msgs
  git:
    repo: https://github.com/Sirius-OIT/urg_node_msgs.git
    dest: ../sirius_ws/src/urg_node_msgs
    version: master

- name: clone laser_proc
  git:
    repo: https://github.com/Sirius-OIT/laser_proc.git
    dest: ../sirius_ws/src/laser_proc
    version: ros2-devel

- name: clone kobuki_core
  git:
    repo: https://github.com/Sirius-OIT/kobuki_core.git
    dest: ../sirius_ws/src/kobuki_core
    version: devel

- name: clone kobuki_ros
  git:
    repo: https://github.com/Sirius-OIT/kobuki_ros.git
    dest: ../sirius_ws/src/kobuki_ros
    version: devel

- name: clone kobuki_velocity_smoother
  git:
    repo: https://github.com/Sirius-OIT/kobuki_velocity_smoother.git
    dest: ../sirius_ws/src/kobuki_velocity_smoother
    version: devel

- name: clone kobuki_ros_interfaces
  git:
    repo: https://github.com/Sirius-OIT/kobuki_ros_interfaces.git
    dest: ../sirius_ws/src/kobuki_ros_interfaces
    version: devel

- name: clone turtlebot3
  git:
    repo: https://github.com/Sirius-OIT/turtlebot3.git
    dest: ../sirius_ws/src/turtlebot3
    version: foxy-devel

- name: add line to bashrc
  lineinfile: dest={{ ansible_env.HOME }}/.bashrc line="source /opt/ros/foxy/setup.bash"
  
- name: colcon build
  shell: |
    cd ../sirius_ws 
    source /opt/ros/foxy/setup.bash
    colcon build