- name: clone urg_node
  git:
    repo: https://github.com/Sirius-OIT/urg_node.git
    dest: ../sirius_ws/src/urg_node
    version: ros2-devel

- name: clone urg_c
  git:
    repo: https://github.com/Sirius-OIT/urg_c.git
    dest: ../sirius_ws/src/urg_c
    version: ros2-devel

- name: clone urg_node_msgs
  git:
    repo: https://github.com/Sirius-OIT/urg_node_msgs.git
    dest: ../sirius_ws/src/urg_node_msgs
    version: master

- name: clone laser_proc
  git:
    repo: https://github.com/Sirius-OIT/laser_proc.git
    dest: ../sirius_ws/src/laser_proc
    version: ros2-devel

- name: clone kobuki_core
  git:
    repo: https://github.com/Sirius-OIT/kobuki_core.git
    dest: ../sirius_ws/src/kobuki_core
    version: devel

- name: clone kobuki_ros
  git:
    repo: https://github.com/Sirius-OIT/kobuki_ros.git
    dest: ../sirius_ws/src/kobuki_ros
    version: humble-devel

- name: clone kobuki_velocity_smoother
  git:
    repo: https://github.com/Sirius-OIT/kobuki_velocity_smoother.git
    dest: ../sirius_ws/src/kobuki_velocity_smoother
    version: devel

- name: clone kobuki_ros_interfaces
  git:
    repo: https://github.com/Sirius-OIT/kobuki_ros_interfaces.git
    dest: ../sirius_ws/src/kobuki_ros_interfaces
    version: devel

- name: clone ecl_tools
  git:
    repo: https://github.com/stonier/ecl_tools.git
    dest: ../sirius_ws/src/ecl_toos
    version: devel

- name: clone ecl_core
  git:
    repo: https://github.com/stonier/ecl_core.git
    dest: ../sirius_ws/src/ecl_core
    version: devel

- name: clone ecl_lite
  git:
    repo: https://github.com/stonier/ecl_lite.git
    dest: ../sirius_ws/src/ecl_lite
    version: devel

- name: clone Sophus
  git:
    repo: https://github.com/Sirius-OIT/Sophus.git
    dest: ../Sophus
    version: main-1.x

- name: clone velodyne
  git:
    repo: https://github.com/Sirius-OIT/velodyne.git
    dest: ../sirius_ws/src/velodyne
    version: ros2

- name: clone slam_toolbox
  git:
    repo: https://github.com/Sirius-OIT/slam_toolbox.git
    dest: ../sirius_ws/src/slam_toolbox
    version: ros2

- name: clone navigation2
  git:
    repo: https://github.com/Sirius-OIT/navigation2.git
    dest: ../sirius_ws/src/navigation2
    version: main
