- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Get Ubuntu Version
  shell: lsb_release -cs
  register: ubuntu_version

- name: apt update
  become: yes
  apt:
    update_chache: yes

- name: install docker dependencies packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: add docker repository GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to APT source
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch={{deb_architecture.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ubuntu_version.stdout}} stable
    state: present

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: docker install
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  notify:
    - add_user_to_docker-group
    - restart_docker-daemon
  changed_when: yes

- meta: flush_handlers